### PR TITLE
Milestone 3 implement friendships with only two rows

### PR DESCRIPTION
**Pull request by Yors-git**
In this pull request the code shows how the associations between the user model and itself for creating friendships are done with only two lines.
- When a friendship is created, an inverse_friendship is automatically created also, to reflect that request to the invited user.
- Is possible to find user's friends in friendship table by user_id.
- Is possible to access the requests sent from the user to another user through the friends method on that user.
- Is possible to access the requests sent to the user from another user through the inverse_friendships method on that user.

### CODE REVIEW

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

#### Hey team,  your project is looking really good, however, to accomplish as the actual project, you required to do these changes, listed below:

 
## [REQUIRED CHANGES]
- [x] Your PR could be more descriptive;
- [x] You should start updating your README by now;

- [x] Please note that the main purpose of this project is to create an additional row with reversed user-friend pair is created. If you feel any challenge, please refer to this [article](https://explainextended.com/2009/03/07/selecting-friends) and this [StackOverflow](https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table) discussion as a hint.

- [x] When friendship is confirmed, an additional row with reversed user-friend pair is created.

```
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
- [x] Thanks to this, we can find user friends only by user_id in friendships table
```
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```
- [x] User #pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```
- [x] User #friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```
- [x] In order to get all posts written by user on their friends, you can use simple method in User model (in order to NOT do it with Enumerables)
```
# User model

def friends_and_own_posts
  Post.where(user: (self.friends << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In the real world, you'll have a lot of change requests for your real clients, it's good to get used to it.</sub>

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
### Hi, @Yors-git, coming this far already makes you amazing 👍 

Let's quickly address some of the changes requested by the previous TSE that you missed out on. 
I guess that's why they call it friendship V2 😄 , the implementation is slightly different, why? More emphasis is been laid on association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

So let's address those changes again.

- [x] When friendship is confirmed, an additional row with reversed user-friend pair is created
```ruby
def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```

- [x]  thanks to this, we can find user friends only by user_id in the friendships table
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

- [x] User #pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```

- [x] User #friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

- [x] In order to get all posts written by user on their friends, students can use simple method in User model (in order to NOT do it with Enumerables)

```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

- [x] Great use of capybara, add more tests coverage for your unit test, post, comment, like seems to be missing. [Shoulda-Matchers](https://github.com/thoughtbot/shoulda-matchers) is great for unit testing you should check it out.
- [x] It will be nice to also have the Accept or Reject request button on the users' list page and on the single-user page

- [x] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.  
See affected files below:

> * `layouts/application.html.erb`
> * `users/_user.html.erb`
> * `users/show.html.erb`

**The Resources below may come in handy**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

 ### Impressive progress @Yors-git, really amazing 👍 👏 👏 

Two of your test are failing, let's quickly fix this and we will be done.

Screen Shot 2020-12-20 at 10 06 44 PM

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by SpaYco — APPROVED** [review]
# Project Approved ✔️ 

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Pull request merged**
